name: DartCompile

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # TODO: Add Windows.
        os: [ ubuntu-latest, macos-latest ]

    steps:
      - uses: actions/checkout@v3

      - uses: dart-lang/setup-dart@a57a6c04cf7d4840e88432aad6281d1e125f0d46
        with:
          sdk: stable
          architecture: x64

      - name: Print SHA
        run: echo "SHA -- $GITHUB_SHA"

      - name: Install Dart dependencies
        run: dart pub get

      - name: Compile to executable
        run: USE_DART=1 bin/x self compile

      - name: Setup git config
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Check if executable files are changed
        id: check_changes
        run: |
          echo "GIT_STATUS=$(git status --porcelain bin/compiled)" >> $GITHUB_OUTPUT

      - name: Commit and push the executable files
        # Only commit if there are changes.
        if: ${{ steps.check_changes.outputs.GIT_STATUS != '' }}
        run: |
          git add bin/compiled/
          git commit -m "Compile to executable on '${{ matrix.os }}'"
          git pull --rebase
          git push
